spring:
  datasource:
    url: jdbc:hsqldb:file:test/.hsqldb/testdb;shutdown=true
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
server:
  error:
    whitelabel:
      enabled: false
    include-message: always